language: python
python:
  - '3.6'
cache: pip
install:
  - pip install -e .
  - pip install -e '.[test]'
  - pip install codecov
  - cp ci/test_settings.py test_settings.py
  - python -c "import uuid; print('SECRET_KEY = \'%s\'' % uuid.uuid4())" >> test_settings.py
script:
  - python -m pytest --cov=django_oaipmh
after_success:
  - codecov
notifications:
  email: false