language: python
python:
  - '3.6'
install:
  - pip install -e .
  - pip install -e '.[test]'
  - pip install codecov
  - cp ci/testsettings.py testsettings.py
  - python -c "import uuid; print('SECRET_KEY = \'%s\'' % uuid.uuid4())" >> testsettings.py
script:
  - python -m pytest --cov=django_oaipmh
after_success:
  - codecov
